<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto

namespace GPBMetadata;

class Math
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe020a0a6d6174682e70726f746f120964656d6f2e6d61746822220a0a" .
            "4164644d65737361676512090a017818012001280512090a017918022001" .
            "2805221d0a0b416464526573706f6e7365120e0a06726573756c74180120" .
            "01280522270a0f53756274726163744d65737361676512090a0178180120" .
            "01280512090a017918022001280522220a10537562747261637452657370" .
            "6f6e7365120e0a06726573756c741801200128053287010a0a43616c6375" .
            "6c61746f7212340a0341646412152e64656d6f2e6d6174682e4164644d65" .
            "73736167651a162e64656d6f2e6d6174682e416464526573706f6e736512" .
            "430a085375627472616374121a2e64656d6f2e6d6174682e537562747261" .
            "63744d6573736167651a1b2e64656d6f2e6d6174682e5375627472616374" .
            "526573706f6e73654203d00201620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

