<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto

namespace Demo\Math;

/**
 * Protobuf type <code>demo.math.Calculator</code>
 */
interface CalculatorInterface
{
    /**
     * Method <code>add</code>
     *
     * @param \Demo\Math\AddMessage $request
     * @return \Demo\Math\AddResponse
     */
    public function add(\Demo\Math\AddMessage $request);

    /**
     * Method <code>subtract</code>
     *
     * @param \Demo\Math\SubtractMessage $request
     * @return \Demo\Math\SubtractResponse
     */
    public function subtract(\Demo\Math\SubtractMessage $request);

}

